[app]
name = "EMFight"
category = "Games"
wifi_preference = "wifiRequired"

[entry]
class = "EMFightApp"

[metadata]
author = "JonTheNiceGuy"
license = "Unlicense"
url = "https://github.com/JonTheNiceGuy/tildagon-emfight"
description = "Badge fight game for EMF Camp — challenge other badge holders!"
version = "0.0.1"
